FirstProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
    path('introne/', include("introne.urls"))
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("daniele", views.daniele, name="daniele"),
    path("<str:name>", views.greet, name="greet")
]

introne/urls.py
from django.urls import path
from . import views

app_name = "introne"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

introne/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def daniele(request):
    return HttpResponse("Hello, Daniele!")

def greet(request, name):
    return render(request, "hello/index.html", {"name": name.capitalize()})

introne/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    #priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

tasks = []

def index(request):
    return render(request, "introne/index.html", {
        "tasks": tasks
    })

def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
            return HttpResponseRedirect(reverse("introne:index"))
        else:
            return render(request, "introne/add.html", {
                "form": form
            })
    return render(request, "introne/add.html",{
        "form": NewTaskForm()
    })

newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })
     

tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    #priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.

def index(request):
    if "tasks" not in request.session:  #request.sessions is like a big dictionary
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    return render(request, "tasks/add.html",{
        "form": NewTaskForm()
    })

hello/templates/hello/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>
            Hello, {{name}}!
        </h1>
    </body>
</html>

introne/templates/introne/add.html
{% extends "introne/layout.html" %}

{% block body %}
    <!-- Add tasks, forms-->
    <!-- Will take actions-->
    <h1>Add comment:</h1>
    <form action="{% url 'introne:add' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

    <a href="{% url 'introne:index' %}">View comments</a>
{% endblock %}

introne/templates/introne/index.html
{% extends "introne/layout.html" %}

{% block body %}
    <!-- Loop syntax -->
    <h1>Comments:</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No comments.</li>
        {% endfor %}
    </ul>
    <!-- django understand link by path name -->
    <a href="{% url 'introne:add' %}">Add a new comments</a>
{% endblock %}

introne/templates/introne/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Introne</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

newyear/templates/newyear/index.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>
            Is it New Year's?
        </title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- Logic syntax -->
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}

    </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <!-- Add tasks, forms-->
    <!-- Will take actions-->
    <h1> Add tasks:</h1>
    <form action="{% url 'tasks:add' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

    <a href="{% url 'tasks:index' %}">View tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <!-- Loop syntax -->
    <h1> Tasks:</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <!-- django understand link by path name -->
    <a href="{% url 'tasks:add' %}">Add a new tasks</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>